services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supplier-order-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_VERSION=v1
      - LOG_LEVEL=info
    volumes:
      # Mount source code for development (hot reload)
      # Comment out for production
      - ./src:/app/src:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - supplier-network

networks:
  supplier-network:
    driver: bridge

